# Generated by Django 3.1 on 2020-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonorMatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicalls',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='api_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
